
// Course Data
export const courses = [
    {
        id: 1,
        title: "HTML Complete Course",
        titleKh: "វគ្គសិក្សា HTML ពេញលេញ",
        category: "Web Development",
        categoryKh: "អភិវឌ្ឍន៍គេហទំព័រ",
        level: "Beginner",
        levelKh: "កម្រិតដំបូង",
        price: 25,
        duration: "10 Hours",
        rating: 4.7,
        students: 320,
        image: "./images/p1.png"
    },
    {
        id: 2,
        title: "CSS Mastery",
        titleKh: "វគ្គសិក្សា CSS",
        category: "Web Development",
        categoryKh: "អភិវឌ្ឍន៍គេហទំព័រ",
        level: "Beginner",
        levelKh: "កម្រិតដំបូង",
        price: 30,
        duration: "12 Hours",
        rating: 4.8,
        students: 280,
        image: "./images/p2.png"
    },
    {
        id: 3,
        title: "JavaScript Fundamentals",
        titleKh: "មូលដ្ឋានគ្រឹះ JavaScript",
        category: "Web Development",
        categoryKh: "អភិវឌ្ឍន៍គេហទំព័រ",
        level: "Beginner",
        levelKh: "កម្រិតដំបូង",
        price: 40,
        duration: "18 Hours",
        rating: 4.9,
        students: 550,
        image: "./images/p3.png"
    },
    {
        id: 4,
        title: "Advanced JavaScript",
        titleKh: "JavaScript កម្រិតខ្ពស់",
        category: "Web Development",
        categoryKh: "អភិវឌ្ឍន៍គេហទំព័រ",
        level: "Advanced",
        levelKh: "កម្រិតខ្ពស់",
        price: 65,
        duration: "22 Hours",
        rating: 4.9,
        students: 240,
        image: "./images/p4.png"
    },
    {
        id: 5,
        title: "Bootstrap 5",
        titleKh: "វគ្គសិក្សា Bootstrap 5",
        category: "Web Development",
        categoryKh: "អភិវឌ្ឍន៍គេហទំព័រ",
        level: "Beginner",
        levelKh: "កម្រិតដំបូង",
        price: 20,
        duration: "8 Hours",
        rating: 4.6,
        students: 400,
        image: "./images/p5.png"
    },
    {
        id: 6,
        title: "Tailwind CSS",
        titleKh: "វគ្គសិក្សា Tailwind CSS",
        category: "Web Development",
        categoryKh: "អភិវឌ្ឍន៍គេហទំព័រ",
        level: "Intermediate",
        levelKh: "កម្រិតមធ្យម",
        price: 35,
        duration: "14 Hours",
        rating: 4.8,
        students: 310,
        image: "./images/p6.png"
    },
    {
        id: 7,
        title: "React JS",
        titleKh: "វគ្គសិក្សា React JS",
        category: "Frontend Framework",
        categoryKh: "Framework ខាងមុខ (Frontend)",
        level: "Intermediate",
        levelKh: "កម្រិតមធ្យម",
        price: 75,
        duration: "30 Hours",
        rating: 4.9,
        students: 670,
        image: "./images/p7.png"
    },
    {
        id: 8,
        title: "Next.js",
        titleKh: "វគ្គសិក្សា Next.js",
        category: "Frontend Framework",
        categoryKh: "Framework ខាងមុខ (Frontend)",
        level: "Advanced",
        levelKh: "កម្រិតខ្ពស់",
        price: 90,
        duration: "35 Hours",
        rating: 4.8,
        students: 210,
        image: "./images/p8.png"
    },
    {
        id: 9,
        title: "Vue.js",
        titleKh: "វគ្គសិក្សា Vue.js",
        category: "Frontend Framework",
        categoryKh: "Framework ខាងមុខ (Frontend)",
        level: "Intermediate",
        levelKh: "កម្រិតមធ្យម",
        price: 70,
        duration: "25 Hours",
        rating: 4.7,
        students: 180,
        image: "./images/p9.png"
    },
    {
        id: 10,
        title: "Python Programming",
        titleKh: "សរសេរកម្មវិធី Python",
        category: "Programming",
        categoryKh: "សរសេរកម្មវិធី",
        level: "Beginner",
        levelKh: "កម្រិតដំបូង",
        price: 50,
        duration: "20 Hours",
        rating: 4.9,
        students: 800,
        image: "./images/p10.png"
    },
    {
        id: 11,
        title: "Python OOP",
        titleKh: "Python OOP",
        category: "Programming",
        categoryKh: "សរសេរកម្មវិធី",
        level: "Intermediate",
        levelKh: "កម្រិតមធ្យម",
        price: 60,
        duration: "18 Hours",
        rating: 4.8,
        students: 260,
        image: "./images/p11.png"
    },
    {
        id: 12,
        title: "Python Django",
        titleKh: "Web Development with Django",
        category: "Backend Development",
        categoryKh: "អភិវឌ្ឍន៍ Backend",
        level: "Advanced",
        levelKh: "កម្រិតខ្ពស់",
        price: 95,
        duration: "40 Hours",
        rating: 4.9,
        students: 150,
        image: "./images/p12.png"
    },
    {
        id: 13,
        title: "PHP & MySQL",
        titleKh: "PHP និង MySQL",
        category: "Backend Development",
        categoryKh: "អភិវឌ្ឍន៍ Backend",
        level: "Intermediate",
        levelKh: "កម្រិតមធ្យម",
        price: 55,
        duration: "24 Hours",
        rating: 4.7,
        students: 340,
        image: "./images/p13.png"
    },
    {
        id: 14,
        title: "Laravel Framework",
        titleKh: "Laravel Framework",
        category: "Backend Development",
        categoryKh: "អភិវឌ្ឍន៍ Backend",
        level: "Advanced",
        levelKh: "កម្រិតខ្ពស់",
        price: 85,
        duration: "32 Hours",
        rating: 4.8,
        students: 220,
        image: "./images/p14.png"
    },
    {
        id: 15,
        title: "Node.js",
        titleKh: "Node.js Backend Development",
        category: "Backend Development",
        categoryKh: "អភិវឌ្ឍន៍ Backend",
        level: "Intermediate",
        levelKh: "កម្រិតមធ្យម",
        price: 80,
        duration: "28 Hours",
        rating: 4.8,
        students: 390,
        image: "./images/p15.png"
    },
    {
        id: 16,
        title: "Express.js",
        titleKh: "Express.js",
        category: "Backend Development",
        categoryKh: "អភិវឌ្ឍន៍ Backend",
        level: "Intermediate",
        levelKh: "កម្រិតមធ្យម",
        price: 60,
        duration: "15 Hours",
        rating: 4.7,
        students: 175,
        image: "./images/p16.png"
    },
    {
        id: 17,
        title: "UI/UX Design",
        titleKh: "រចនា UI/UX",
        category: "Design",
        categoryKh: "ការរចនា",
        level: "Beginner",
        levelKh: "កម្រិតដំបូង",
        price: 45,
        duration: "16 Hours",
        rating: 4.8,
        students: 450,
        image: "./images/p17.png"
    },
    {
        id: 18,
        title: "Figma for Beginners",
        titleKh: "Figma សម្រាប់អ្នកចាប់ផ្តើម",
        category: "Design",
        categoryKh: "ការរចនា",
        level: "Beginner",
        levelKh: "កម្រិតដំបូង",
        price: 35,
        duration: "12 Hours",
        rating: 4.7,
        students: 500,
        image: "./images/p18.png"
    },
    {
        id: 19,
        title: "Adobe Photoshop",
        titleKh: "Adobe Photoshop",
        category: "Design",
        categoryKh: "ការរចនា",
        level: "Intermediate",
        levelKh: "កម្រិតមធ្យម",
        price: 50,
        duration: "18 Hours",
        rating: 4.6,
        students: 270,
        image: "./images/p19.png"
    },
    {
        id: 20,
        title: "Flutter Mobile App",
        titleKh: "ការអភិវឌ្ឍកម្មវិធី Flutter",
        category: "Mobile Development",
        categoryKh: "អភិវឌ្ឍន៍ Mobile",
        level: "Intermediate",
        levelKh: "កម្រិតមធ្យម",
        price: 85,
        duration: "35 Hours",
        rating: 4.9,
        students: 300,
        image: "./images/p20.png"
    }
];

// Why Data
export const whyStudy = [
    {
        title: "💻 រៀនតាម Google Meet",
        des: "រៀនផ្ទាល់ជាមួយគ្រូតាម Google Meet មាន interaction ពិតៗ"
    },
    {
        title: "🤝 ការបង្រៀន",
        des: "គ្រូបង្រៀន step-by-step និងឲ្យសិស្សអនុវត្តក្នុងថ្នាក់ភ្លាមៗ"
    },
    {
        title: "🚀 Support ពេលរៀនt",
        des: "សិស្សអាចសួរភ្លាមៗ ពេលមានចម្ងល់"
    },
    {
        title: "🎥 វីដេអូមានគុណភាព",
        des: "បន្ទាប់ពីរៀនមាន record វីដេអូទុកសម្រាប់ជំនួយដល់សិស្ស"
    },
]


